<?php require APPROOT.'/views/client/header.php';?>
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css">
    <link rel="stylesheet" href="<?php echo URLROOT; ?>/css/client/installation.css">

</head>

<body>
    <?php require APPROOT.'/views/inc/components/topnavbar.php'; ?>


    <!-- Sidebar -->
    <div class="sidebar">
        <!-- <a href="#" class="logo">
            <i class='bx bx-code-alt'></i>
            <div class="logo-name"><span>Asmr</span>Prog</div>
        </a> -->
        <ul class="side-menu">
            <li ><a href="#" style="background-color: rgb(192, 236, 192);" class="back-buttons"><i class='bx bx-arrow-back'></i>Back</a></li>
            <li ><a href="Dashboard.html"><i class='bx bxs-dashboard'></i>Dashboard</a></li>
            <li class="active"><a href="Project.html"><i class='bx bx-analyse'></i>Project</a></li>
            <li ><a href="#"><i class='bx bx-store-alt'></i>Shop</a></li>
            <li><a href="#"><i class='bx bx-message-square-dots'></i>Chat</a></li>
            <!-- <li><a href="#"><i class='bx bx-group'></i>Users</a></li> -->
            <li><a href="#"><i class='bx bx-cog'></i>Settings</a></li>
        </ul>
        <ul class="side-menu">
            <li>
                <a href="#" class="logout">
                    <i class='bx bx-log-out-circle'></i>
                    Logout
                </a>
            </li>
        </ul>
    </div>
    <!-- End of Sidebar -->

    <!-- Main Content -->
    <div class="content">
        <!-- Navbar -->
        <nav>
            <i class='bx bx-menu'></i>
        </nav>

        <div class="container">
            <div class="card">
                <div class="date-display">
                    <h2>Your installation day Schedule</h2>
                    <div class="status-badge">Pending Review</div>
                    <div class="date-number" id="visitDate">Nov 10</div>
                    <div class="time-display" id="visitTime">7 AM</div>
                    <div class="button-group">
                        <button class="btn-visit btn-primary" onclick="confirmDate()">Confirm Schedule</button>
                        <button class="btn-visit btn-secondary" onclick="showDatePicker()">Change Schedule</button>
                    </div>
                </div>
                <div class="calendar">
                    <div class="calendar-header">
                        <h3 id="currentMonth">November 2024</h3>
                    </div>
                    <div class="calendar-grid" id="calendarGrid">
                        <!-- Calendar days will be generated by JavaScript -->
                    </div>
                </div>
            </div>
        </div>
        <div class="toast-container" id="toastContainer"></div>

        <div class="popup" id="datePickerPopup">
            <h3>Select New Schedule</h3>
            <form id="scheduleForm" onsubmit="return false;">
                <div class="form-group">
                    <label for="dateInput">Date</label>
                    <input type="date" id="dateInput" class="form-control" required>
                </div>
                <div class="form-group">
                    <label for="timeInput">Time</label>
                    <input type="time" id="timeInput" class="form-control" required>
                </div>
                <div class="button-group">
                    <button class="btn-visit btn-primary" onclick="confirmNewDate()">Confirm</button>
                    <button class="btn-visit btn-secondary" onclick="closeDatePicker()">Cancel</button>
                </div>
            </form>
        </div>
        <!-- End of Navbar -->


    </div>
    <div class="overlay" id="overlay"></div>

</body>
    <script src="<?php echo URLROOT; ?>/js/client/installation.js"></script>
<?php require APPROOT.'/views/packages/footer.php';?>

