<?php require APPROOT.'/views/client/header.php';?>
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.4.120/pdf.min.js"></script>
    <link rel="stylesheet" href="<?php echo URLROOT; ?>/css/client/sitevisit.css">

</head>
<body>
    <?php require APPROOT.'/views/inc/components/topnavbar.php'; ?>


    <!-- Sidebar -->
    <div class="sidebar">
    <ul class="side-menu">
    <a href="<?php echo URLROOT; ?>/client/project" style="background-color: rgb(192, 236, 192);" class="back-buttons"><i class='bx bx-arrow-back'></i>Back</a></li>
        </ul>
        <ul class="side-menu">
            <li>
                <a href="<?php echo URLROOT; ?>/users/logout" class="logout">
                    <i class='bx bx-log-out-circle'></i>
                    Logout
                </a>
            </li>
        </ul>
    </div>
    <!-- End of Sidebar -->

    <div class="content">
            <!-- Navbar -->
            <nav>
                <i class='bx bx-menu'></i>
            </nav>

            <!-- End of Navbar -->
            <div class="container">
                <div class="card">
                    <div class="date-display">
                        <h2>Your site visit Schedule</h2>
                        <div class="date-number" id="visitDate">Nov 10</div>
                        <div class="time-display" id="visitTime">2:30 PM</div>
                        <div class="button-group">
                            <button class="btn btn-primary" onclick="confirmDate()">Confirm Schedule</button>
                            <button class="btn btn-secondary" onclick="showDatePicker()">Change Schedule</button>
                        </div>
                    </div>
                    <div class="calendar">
                        <div class="calendar-header">
                            <h3 id="currentMonth">November 2024</h3>
                        </div>
                        <div class="calendar-grid" id="calendarGrid">
                            <!-- Calendar days will be generated by JavaScript -->
                        </div>
                    </div>
                </div>
            </div>
            <div class="toast-container" id="toastContainer"></div>

            <div class="popup" id="datePickerPopup">
                <h3>Select New Schedule</h3>
                <form id="scheduleForm" onsubmit="return false;">
                    <div class="form-group">
                        <label for="dateInput">Date</label>
                        <input type="date" id="dateInput" class="form-control" required>
                    </div>
                    <div class="form-group">
                        <label for="timeInput">Time</label>
                        <input type="time" id="timeInput" class="form-control" required>
                    </div>
                    <div class="button-group">
                        <button class="btn btn-primary" onclick="confirmNewDate()">Confirm</button>
                        <button class="btn btn-secondary" onclick="closeDatePicker()">Cancel</button>
                    </div>
                </form>
            </div>
 
        </div>
        <div class="overlay" id="overlay"></div>



        <script src="<?php echo URLROOT; ?>/js/client/sitevisit.js"></script>
<?php require APPROOT.'/views/client/footer.php';?>